version: "3.8"

services:
  db-service:
      container_name: dev-database
      image: mysql
      volumes:
        - ./mysql:/var/lib/mysql
      env_file: .env
      environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
      ports:
        - ${MYSQL_DEVDB_PORT}:${MYSQL_DEVDB_DOCKER_PORT}
  app:
    container_name: scout-api-dev
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./.wwebjs_auth/session-client-master/:/.wwebjs_auth/session-client-master
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_US_CHAT_ID=${WHATSAPP_US_CHAT_ID}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - db-service
    links: 
      - db-service