version: "3.8"

services:
  app:
    container_name: scout-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes: 
      - ./.wwebjs_auth/session-client-master/:/.wwebjs_auth/session-client-master
    env_file: .env.production
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_US_CHAT_ID=${WHATSAPP_US_CHAT_ID}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}