version: "3.8"

services:
  # db-service:
  #     container_name: dev-database
  #     image: mysql
  #     user: root
  #     volumes:
  #       - ./mysql-data:/var/lib/mysql
  #     env_file: .env
  #     environment:
  #       - MYSQL_ROOT_PASSWORD=${MYSQL_DEVDB_PASSWORD}
  #       - MYSQL_DATABASE=${MYSQL_DEVDB_NAME}
  app:
    container_name: scout-api-dev
    restart: always
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../.wwebjs_auth:/.wwebjs_auth
    # env_file: ../.env.development
    #   - PORT=${PORT}
    # depends_on:
    #   - db-service
    # network_mode: service:db-service
